# 项目组织
baseurl = "https://qiansen1386.github.io/"
# 个人定制
title = "东方孤思子的博客（Paris · Qian Sen）"
# 语言
languageCode = "zh-cn"
hasCJKLanguage=true # if true, auto-detect Chinese/Japanese/Korean Languages in the content. (.Summary and .WordCount can work properly in CJKLanguage)
# 其它选项
builddrafts = false
canonifyurls = true
pygmentsUseClasses=true
pygmentsStyle="monokai"
# 主题限定
paginate = 10
theme = "steam"
disqusShortname = "qiansen1386"
[params]
	#通用
	#主题限定
	title = "东方孤思子のBlog"
	subtitle = "Profesional Coding · Simple Living · Creative Thinking"
	copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议 CC 4.0 International" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png" /></a>若无特殊说明，本站内容受<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><b>CC</b>署名-非商业性使用-相同方式共享 4.0 许可协议</a>保护，商业转载许可请另行联系。'
	
	# 四选一 green, orange, red and blue.
	themeColor = "green"
	# Enable Google Analytics be inserting your tracking code
	googleAnalytics = "UA-47725881-1"
	
	# To provide some metadata for search engines and the about section in the footer
	# feel free to add a few information about you and your website.
	name = "东方孤思子"
	bio = "这是个互联网工程师，正义感爆棚的傻X"
	description = "随便写写，主要是技术分享，人生感悟，政治策论等等。"
	location = "Singapore" # optional
	twitter = "qiansen1386" # optional
	github = "qiansen1386" # optional
	
	# Enable a comment system
	# You can choose between Disqus or Google Plus by setting comments
	# to disqus or googleplus. For using Disqus you need to enter your
	# shortname in disqusShortname at the top of the configs. 
	comments = "disqus"
	
	# Customize or translate the strings
	keepReadingStr = "more.."
	backtotopStr = "Top"
	shareStr = "Share"
	pageNotFoundTitle = "404 - 你要找啥？本页不存在诶？"