name = "Placid"
license = "MIT"
licenselink = "https://github.com/qiansen1386/hugo-placid-theme/blob/master/LICENSE"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "https://github.com/qiansen1386/hugo-placid-theme"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]
min_version = 0.15

[author]
  name = "Paris Qian Sen"
  homepage = "https://wwwparisqian.com"

# If porting an existing theme
[original]
  name = "Andrei Mihu"
  homepage = "http://andreimihu.com"
  repo = "https://github.com/zyro/hyde-x"
